### ISSUE TITLE
App crashes while loading 'Cijfers' page

### ISSUE THREAD

**Issue by Radiofreak1041** [Z3r0byte/Magis#35]
Build version: 1.1.4 
Build date: 1979-11-30 00:00:00 
Current date: 2016-09-10 09:45:42 
Device: OnePlus One (A0001)
OS: CyanogenMod 13.0 (Android 6.0.1)

I think 'com.google.gson.JsonArray com.google.gson.JsonElement.getAsJsonArray()' is not initialized properly.

For a few milliseconds the app shows 'geen cijfers' but then it crashes and shows the following:

Stack trace:  
java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$3.done(AsyncTask.java:309)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.gson.JsonArray com.google.gson.JsonElement.getAsJsonArray()' on a null object reference
    at net.ilexiconn.magister.adapter.GradeAdapter.read(GradeAdapter.java:50)
    at net.ilexiconn.magister.adapter.GradeAdapter.read(GradeAdapter.java:39)
    at com.google.gson.Gson.fromJson(Gson.java:879)
    at com.google.gson.Gson.fromJson(Gson.java:817)
    at net.ilexiconn.magister.handler.GradeHandler.getGradesFromStudy(GradeHandler.java:69)
    at com.z3r0byte.magis.Tasks.GradesTask.doInBackground(GradesTask.java:85)
    at com.z3r0byte.magis.Tasks.GradesTask.doInBackground(GradesTask.java:40)
    at android.os.AsyncTask$2.call(AsyncTask.java:295)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    ... 4 more

**Comment by Z3r0byte** [comment]
Thanks for reporting!
Fixed

**Comment by Z3r0byte** [comment]
Bug happens again.
