### ISSUE TITLE
Assertion error causes app to crash.

### ISSUE THREAD

**Issue by Z3r0byte** [Z3r0byte/Magis#53]
Stack trace:

```
Stack trace:  
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:309)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.AssertionError
	at com.google.gson.internal.bind.JsonTreeReader.peek(JsonTreeReader.java:125)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:720)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:718)
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:914)
	at net.ilexiconn.magister.adapter.type.AppointmentTypeAdapter.read(AppointmentTypeAdapter.java:40)
	at net.ilexiconn.magister.adapter.type.AppointmentTypeAdapter.read(AppointmentTypeAdapter.java:30)
	at com.google.gson.TypeAdapter.fromJsonTree(TypeAdapter.java:285)
	at net.ilexiconn.magister.adapter.AppointmentAdapter.read(AppointmentAdapter.java:89)
	at net.ilexiconn.magister.adapter.AppointmentAdapter.read(AppointmentAdapter.java:44)
	at com.google.gson.Gson.fromJson(Gson.java:879)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at net.ilexiconn.magister.handler.AppointmentHandler.getAppointments(AppointmentHandler.java:80)
	at com.z3r0byte.magis.Tasks.AppointmentsTask.doInBackground(AppointmentsTask.java:75)
	at com.z3r0byte.magis.Tasks.AppointmentsTask.doInBackground(AppointmentsTask.java:45)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
```

**Comment by Z3r0byte** [comment]
bug fixed by erasing app data
