### ISSUE TITLE
Boolean isOldFormat in GradesTask.java is null if no internet connection is present.

### ISSUE THREAD

**Issue by rutgerbrf** [Z3r0byte/Magis#73]
Stacktrace:

```
Build version: 1.6.6
Build date: 1979-11-30 00:00:00
Current date: 2018-03-05 08:33:26
Device: LGE Nexus 5X

Stack trace:
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
at com.z3r0byte.magis.Utils.DB_Handlers.GradesDB.getUniqueAverageGrades(GradesDB.java:192)
at com.z3r0byte.magis.Tasks.GradesTask.onPostExecute(GradesTask.java:129)
at com.z3r0byte.magis.Tasks.GradesTask.onPostExecute(GradesTask.java:44)
at android.os.AsyncTask.finish(AsyncTask.java:695)
at android.os.AsyncTask.-wrap1(Unknown Source:0)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by Z3r0byte** [comment]
Thanks for reporting this! I will fix it soon
